### PR TITLE
Switch up how targets groups are associated with the ASG

### PR DESCRIPTION
**Pull request by mcgirr**
Small change to how we associate target groups with the ASG in the `asg` module

- [ ] Update the changelog
- [ ] Make sure that modules and files are documented. This can be done inside the module and files.
- [ ] Make sure that new modules directories contain a basic README.md file.
- [ ] Make sure that the module is added to [tests/main.tf](https://github.com/fpco/terraform-aws-foundation/blob/master/tests/main.tf)
- [ ] Make sure that the linting passes on CI.
- [ ] Make sure that there is an up to date example for your code:
      - For new `modules` this would entail example code for how to use the module or some explanation in the module readme.
      - For new examples please provide a README explaining how to run the example. It's also ideal to provide a basic makefile to use the example as well.
- [ ] Make sure that there is a manual CI trigger that can test the deployment.

### CODE REVIEW

**Comment by mcgirr** [comment]
We're currently using this in practice now and have shown it to work. I can link to examples but I'd like to work to get this reviewed and merged. (And we can updated any places where they refer to the branch in this PR).

**Comment by JoseD92** [comment]
Nice change, I like it, it solve a problem of using both target_group_arns and aws_autoscaling_attachment at the same time, mainly because the default value for the variable was [] that made target_group_arns count as used, which made terraform nuts when planning.

I just add a small change to replace the count for a foreach, as having a count might make the plans horrible if you for example delete one element, it would become a cascade update and might generate some errors in the deployment

**Comment by JoseD92** [comment]
I revert from for each to count as you would get errors like:
```
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
that, although not impossible to solve using for depends_on, makes using the module a bit harder

**Comment by JoseD92** [comment]
as validation, I have made 
[test1.tf](https://github.com/fpco/terraform-aws-foundation/files/4405553/main.tf.txt) that shows the current state of the issue, after applying once, applying again does:

```
Terraform will perform the following actions:

  # module.asg.aws_autoscaling_group.cluster will be updated in-place
  ~ resource "aws_autoscaling_group" "cluster" {
        arn                       = "arn:aws:autoscaling:us-west-2:793514493597:autoScalingGroup:92b5938d-bc1d-4fdf-a6b6-e3579cf5a82d:autoScalingGroupName/jose-cluster20200330211542083500000003"
        availability_zones        = [
            "us-west-2a",
            "us-west-2b",
        ]
        default_cooldown          = 300
        desired_capacity          = 1
        enabled_metrics           = []
        force_delete              = true
        health_check_grace_period = 300
        health_check_type         = "EC2"
        id                        = "jose-cluster20200330211542083500000003"
        launch_configuration      = "terraform-20200330211539726100000002"
        load_balancers            = []
        max_instance_lifetime     = 0
        max_size                  = 1
        metrics_granularity       = "1Minute"
        min_size                  = 1
        name                      = "jose-cluster20200330211542083500000003"
        name_prefix               = "jose-cluster"
        protect_from_scale_in     = false
        service_linked_role_arn   = "arn:aws:iam::793514493597:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        suspended_processes       = []
        tags                      = [
            {
                "key"                 = "Name"
                "propagate_at_launch" = "true"
                "value"               = "jose-cluster"
            },
        ]
      ~ target_group_arns         = [
          - "arn:aws:elasticloadbalancing:us-west-2:793514493597:targetgroup/test1-https-tg/f0b9ae61cd2ac918",
        ]
        termination_policies      = []
        vpc_zone_identifier       = [
            "subnet-022fee224c80dcbdb",
            "subnet-05a6c059ff79508d5",
        ]
        wait_for_capacity_timeout = "10m"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
Terraform will perform the following actions:

  # module.asg.aws_autoscaling_group.cluster will be updated in-place
  ~ resource "aws_autoscaling_group" "cluster" {
        arn                       = "arn:aws:autoscaling:us-west-2:793514493597:autoScalingGroup:92b5938d-bc1d-4fdf-a6b6-e3579cf5a82d:autoScalingGroupName/jose-cluster20200330211542083500000003"
        availability_zones        = [
            "us-west-2a",
            "us-west-2b",
        ]
        default_cooldown          = 300
        desired_capacity          = 1
        enabled_metrics           = []
        force_delete              = true
        health_check_grace_period = 300
        health_check_type         = "EC2"
        id                        = "jose-cluster20200330211542083500000003"
        launch_configuration      = "terraform-20200330211539726100000002"
        load_balancers            = []
        max_instance_lifetime     = 0
        max_size                  = 1
        metrics_granularity       = "1Minute"
        min_size                  = 1
        name                      = "jose-cluster20200330211542083500000003"
        name_prefix               = "jose-cluster"
        protect_from_scale_in     = false
        service_linked_role_arn   = "arn:aws:iam::793514493597:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
        suspended_processes       = []
        tags                      = [
            {
                "key"                 = "Name"
                "propagate_at_launch" = "true"
                "value"               = "jose-cluster"
            },
        ]
      ~ target_group_arns         = [
          - "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxxxxxx:targetgroup/test1-https-tg/xxxxxxxxxxxxxxxx",
        ]
        termination_policies      = []
        vpc_zone_identifier       = [
            "subnet-xxxxxxxxxxxxxxxxxxx",
            "subnet-xxxxxxxxxxxxxxxxxxx",
        ]
        wait_for_capacity_timeout = "10m"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

it removes the target_group_arns even though no change has been done. Applying another time I get:

```
Terraform will perform the following actions:

  # aws_autoscaling_attachment.asg_alb will be created
  + resource "aws_autoscaling_attachment" "asg_alb" {
      + alb_target_group_arn   = "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxxxx:targetgroup/test1-https-tg/xxxxxxxxxxxxxxxxx"
      + autoscaling_group_name = "jose-clusterxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      + id                     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

restoring the aws_autoscaling_attachment, after that apply will loop the two last changes every time I apply. I add 
[test2.tf](https://github.com/fpco/terraform-aws-foundation/files/4405632/main.tf.txt) which uses this MR on the asg and applying multiple times results in no changes

**Comment by mcgirr** [comment]
I'm going to hold off deleting the branch for now until I've updated the places internally where this is used (but I will remove it soon).

**Pull request merged**
