### PR TITLE
Pass the alb_target_group_arns to the ASG in the SNASG module

### PR DESCRIPTION
**Pull request by mcgirr**
Closes https://github.com/fpco/terraform-aws-foundation/issues/316

### CODE REVIEW

**Comment by mcgirr** [comment]
Okay will do!

**Comment by ketzacoatl** [comment]
ping

**Comment by mcgirr** [comment]
I've added a basic example to this PR in the the examples directory. The code in that uses the changes made for this PR to the single node autoscaling group. 

The example is able to plan and apply

```
Apply complete! Resources: 24 added, 0 changed, 0 destroyed.  
```

**Comment by mcgirr** [comment]
@ketzacoatl Please let me know if that's enough validation for this or if you'd prefer to have more output from that. I can update the CHANGELOG after we merge this to mention the changes to the SNASG module as well as the new example.

**Pull request merged**
